version: '2'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    volumes:
      - /Users/sompong/Jenkins-WorkSpace:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker 
  postgres:
    image: postgres
    container_name: postgres  
    restart: always
    ports:
      - "5432:5432"
    networks:
      - jenkins
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    volumes:
      - /Users/sompong/WorkSpace-Postgres:/var/lib/postgresql
  sonarqube:
    # build:
      # dockerfile: Dockerfile
      # context: ./sonarqube
    image: sonarqube:8.9-community
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - jenkins
    environment:
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonarpasswd
      SONAR_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
      # ES_JAVA_HOME: /opt/java/openjdk/bin
    volumes:
      - /Users/sompong/WorkSpace-Sonarqube/data:/opt/sonarqube/data
      - /Users/sompong/WorkSpace-Sonarqube/logs:/opt/sonarqube/logs
      - /Users/sompong/WorkSpace-Sonarqube/extensions:/opt/sonarqube/extensions
    depends_on: 
      - postgres

networks:
  jenkins:
    # driver: bridge


